site_name: Edu_Platform

theme:
  name: material

nav:
  - Home: index.md
  - Roadmap: roadmap.md
  - Rules: rules.md
  - Courses:
    - Python for Ops:
      - Module 01: courses/python-for-ops/module-01/lesson.md
    - Grade 7 Physics:
      - Lesson 1 Energy And Changes: courses/G7-Physics-MPA-students/lesson1/lesson1_energy_and_changes.md
      - Lesson 2a b How Do Our Bodies Use Energy?: courses/G7-Physics-MPA-students/lesson2/Lesson2-energy-from-food.md
      - Lesson 2c Energy From Food: courses/G7-Physics-MPA-students/lesson2/Lesson_2_C_Energy_Requirement_in_Diet.md
      - Lesson 3 Energy Transfer and Store: courses/G7-Physics-MPA-students/lesson2/energy_transfer_and_store	
    - Grade 8 Chemistry:
      - Lesson 1 Energy And Changes: courses/G7-Physics-MPA-	        students/lesson1/lesson1_energy_and_changes.md	

    - Grade 8 Physics:
      - Lesson 1 State-Of-Matter: courses/G8-Physics_MPA_students/lesson1-state-of-matter.md
      - Lesson 2 Particle-Model: courses/G8-Physics_MPA_students/lesson2-Particle-Model-Expansion-Contraction-Density.md